### ISSUE TITLE
Item slot too less/not scroll-able 

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#13]

**Comment by xBuyax** [comment]
Hi,

as far as I know back then in GMS there weren't much slots by default.
But still it can be considered to have more.

**Comment by imbawind** [comment]
I remember it should at least has more than one page of slots, or I just remembered it wrong.

**Comment by xBuyax** [comment]
Hi,

maybe with old MS pictures or videos we can find it out, I will try to look for that.

**Comment by xBuyax** [comment]
Hi,

after looking for old videos/pictures, I am not 100% sure, but it would be alright to add more slots.
I will think something out but if you have ideas for a good amount, make a pull request or tell me.

Greetings

Buya

**Comment by xBuyax** [comment]
Hi,

currently it's 24 (4*6) slots per inventory.
How about doubling it to 48 (8*6)?

**Comment by imbawind** [comment]
Yeah, looks good.

**Comment by xBuyax** [comment]
Hi, I just commited increase of the slots to 48. (github messed up the numbers in my previous comment because i used * there)
Also I fixed saving of storage items and updated the bug list and feature to-do list.

Keep in mind that the character table needs to be changed manually to set the slots to 48 default with alter table. The sql file was altered this way. Also the existing characters need it manually changed in characters table.

Now that it is fixed, I close this.
