### ISSUE TITLE
Unable to login after creating character.

### ISSUE THREAD

**Issue by CheesesCries** [xBuyax/xanadu#20]
Titles says it all, Unable to login after character creation.. Ever since the latest commit not sure if  i'm the only one having this issue.

**Comment by xBuyax** [comment]
Hi,
that's because a new coloumn to multiple mysql tables was introduced.
You need to add it manually: flags INT NOT NULL DEFAULT '0' to items, storage_equips, storage_items, merchant_storage_equips and merchant_storage_items. you could also just create a new fresh database for it instead of adjusting the existing.

but I will consider adding a mechanism for easy adjusting by users after changes to database tables occur.
